name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Update Ruby Setup
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use a more recent Ruby version
          bundler-cache: true

      # Simplified Dependency Installation
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Build Jekyll Site
      - name: Build Jekyll Site
        run: bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
